-- ~/.config/nvim/lua/tacovim/custom_keymaps.lua
-- Custom Keymaps - Auto-generated by TacoVim Keymap Manager
-- You can manually add your own keymaps here or use the keymap manager (<leader>uk)

-- Example custom keymaps:
-- vim.keymap.set("n", "<leader>cc", "<cmd>ColorizerToggle<cr>", { desc = "Toggle colorizer", silent = true })

-- Your custom keymaps will be appended below this line: 